### PR TITLE
replaced icon

### PR DESCRIPTION
**Pull request by perdolka**
deleted 48.png
added 48.svg
reduced size - from 442  to  288 bytes

### CODE REVIEW

**Comment by vaeth** [comment]
I am not sure whether this will work: According to
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons
there must be some viewbox specified which does not seem to be the case.
Actually, when I had decided about the format in the first version of the extension, I had read about some problems with svg. (The icon must not only work in the toolbar but also in the list of extensions and on mozilla's various webpages.) That's why I am overly careful now before merging.
Of course, an svg would be nicer than a png even if it would be longer...

**Comment by vaeth** [comment]
Merging experimentally

**Comment by perdolka** [comment]
Also, I thought about adding a favicon.
But strings like: 
`<link rel="icon" type="image/svg+xml" href="data/icons/48.svg"> `
 (inside head ... /head, index.html) 
doesn't work for some reason.
I thought it's because something wrong with svg, but png/ico doesn't work too.
Maybe, need to add something into the manifest?

**Comment by vaeth** [comment]
`href="data/icons/48.svg"` is probably wrong; it should perhaps be `href="../data/icons/48.svg".`
However, I couldn't get it to work, either (trying also with `href="moz-extension://..."`).
Maybe this is related:
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1433813
But OTOH, this is only for firefox on android and seems to indicate that there is no such problem on desktop firefox.

**Pull request merged**
